config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show, :update], controller: :profiles
  resource :profile

  resources :photos do
    resources :comments
    # this is a nested route so you can see all the comments per photo
  end

  get 'home/index'
  get '/contact', to: 'static_pages#contact'
  post '/contact', to: 'static_pages#email'
  root 'photos#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :photo
end

app/models/image_uploader.rb
class ImageUploader < Shrine
end

app/models/photo.rb
class Photo < ApplicationRecord
  include ImageUploader[:image]
  belongs_to :user
  has_many :comments
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :photos
  has_one :profile

  # Join table
  # The people who follow us
  has_and_belongs_to_many :followers, class_name: 'User', join_table: :followers,
  foreign_key: :followed_id, association_foreign_key: :follower_id

  # The people we follow
  has_and_belongs_to_many :following, class_name: 'User', join_table: :followers,
  foreign_key: :follower_id, association_foreign_key: :followed_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post

  def index
    @comments = @photo.comments
    @comment = Comment.new
    # the .all method is inherited from ActiveRecord
  end

  def create
    @comment = @photo.comments.build(comment_params)
    @comment.user = current_user #devise method
    if @comment.save
        flash[:success] = 'Comment added!'
        redirect_to root_path
    end
  end
  private

  def comment_params
  params.require(:comment).permit(:content)
  end

  def set_post
  @photo = Photo.find(params[:photo_id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    @photo = Photo.find(params[:id])
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)
    @photo.user = current_user #devise method
    if @photo.save
        flash[:success] = 'Photo added!'
        redirect_to photos_path
    else
        render 'new'
    end
  end


  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:image, :user_id, :caption)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  def index
    @profiles = Profile.all
  end

  def new
    @profile = Profile.new
  end

  def show
    redirect_to edit_profile_url if @profile.nil?
  end

  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to profile_path, notice: 'Profile was successfully updated.' }
      else
        format.html { redirect_to edit_profile_path, notice: 'Could not update profile.' }
      end
    end
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.user = current_user
    respond_to do |format|
      if @profile.save
        format.html { redirect_to profile_path, notice: 'Profile was successfully created.' }
      else
        format.html { redirect_to edit_profile_path, notice: 'Could not save profile.' }
      end
    end
  end

  def edit
    @profile = Profile.new(user: current_user) if @profile.nil?
  end

  def destroy
  end

  private

  def set_profile
    if params[:id]
      @profile = Profile.find_by!(user_id: params[:id])
    else
      @profile = Profile.find_by(user: current_user)
    end
  end

  def profile_params
    params.require(:profile).permit(:avatar_data, :username, :firstname, :lastname, :bio)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def email
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/comments/index.html.erb
<h1> Photo Comments </h1>
<%= image_tag @photo.image_url, width: 200 %>
<% @comments.each do |comment| %>
<br>
  @<%= comment.user.username %>: <%= comment.content %>
</br>
<% end %>

<%= form_with(model: [@photo, @comment], local: true) do |form| %>
  <div class= "form-group">
    <%= form.label :content %>
    <%= form.text_area :content, class: 'form-control' %>
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/home/index.html.erb
<%= render 'layouts/nav' %>
<%= link_to 'Upload Photo', new_photo_path%>

app/views/layouts/_nav.html.erb
<nav class="navbar sticky-top navbar-light bg-white">
    <%= link_to image_tag("logo.svg"), photos_path %>
    <%= link_to image_tag("profile.svg"), profile_path %>
    <%= link_to image_tag("add_icon.svg"), new_photo_path %>
    <% if user_signed_in? %>
    <%= link_to image_tag("logout.svg"), destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to('Login', new_user_session_path)  %>
    <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instarails</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/photos/_form.html.erb
<div class="container-fluid center">
<%= form_with(model: photo, local: true) do |form| %>
  <% if photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>
      <ul>
      <% photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Image %>:
    <%= form.file_field :image, id: :photo_image_data %>
  </div>

  <div class="field">
    <%= form.label :Caption %>:
    <%= form.text_field :caption, id: :photo_caption %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/photos/_photo.html.erb
<div class="container-fluid center">
<div>
  <% if photo.image_data? %>
    <%= image_tag photo.image_url %>
  <% end %>
  <p><%= photo.title %> | <%= link_to 'Edit', edit_photo_path(photo) %></p>
</div>
</div>

app/views/photos/edit.html.erb
<div class="container-fluid center">
<h1>Editing Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>
</div>

app/views/photos/index.html.erb
<%= render 'layouts/nav' %>
<p id="notice"><%= notice %></p>
<div class="jumbotron jumbotron-fluid">
    <div class="card center">
      <% @photos.each do |photo| %>
        <div class="card-header">
          <strong><%= photo.user.username %></strong>
        </div>
        <div class="card-block center">
        <a href= "<%= photo.image_url %>">
          <img class= "thumbnail" src="<%= photo.image_url %>">
        </a>
        <br>
          <strong><%= link_to "#{photo.user.username} ", user_path(photo.user_id) %></strong>  <%= "#{photo.caption}" %>
        </br>
        <br>
          <%= link_to image_tag('heart.svg') %>
          <%= link_to image_tag('comment.svg') %>
        </br>
            <% photo.comments.each do |comment| %>
            <p>
              <strong> <%= link_to "#{comment.user.username} ", user_path(comment.user_id) %> </strong><%= comment.content %>
            </p>
            <% end %>

            <%= form_for [photo, photo.comments.new] do |form| %>
              <div class= "form-group">
                <%= form.text_area :content, class: 'form-control', placeholder: 'Enter Your Comment.' %>
                <br>
                <%= form.submit :Post, class: 'btn btn-basic' %>
                </br>
              </div>
            <% end %>
        </div>
        <% end %>
    </div>
</div>

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<div class="container-fluid center">
<h1>New Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Back', photos_path %>
</div>

app/views/photos/show.html.erb
<div class="container-fluid center">
<p id="notice"><%= notice %></p>

<p>
  <img src="<%= @photo.image_url %>">
</p>

<p>
  <strong><%= @photo.user.username %>:</strong>
  <%= @photo.caption %>
</p>

<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>
</div>

app/views/profiles/create.html.erb
<h1>Profiles#create</h1>
<p>Find me in app/views/profiles/create.html.erb</p>

app/views/profiles/edit.html.erb
<h1>Edit Your Profile</h1>
<div class="container-fluid center">
<%= form_with(model: @profile, url: profile_path, local: true) do |form| %>

  <div class="form-group">
    <%= form.label :Avatar %>:
    <%= form.file_field :image, id: :photo_image_data %>
  </div>

  <div class="form-group">
    <%= form.text_field :firstname, class: 'form-control', placeholder: 'First Name' %>
  </div>

  <div class="form-group">
    <%= form.text_field :lastname, class: 'form-control', placeholder: 'Last Name' %>
  </div>

  <div class="form-group">
    <%= form.text_area :bio, class: 'form-control', placeholder: 'Bio' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/profiles/new.html.erb
<h1>Profiles#new</h1>
<p>Find me in app/views/profiles/new.html.erb</p>

app/views/profiles/show.html.erb
<%= render 'layouts/nav' %>
  <div class="card center">
    <h1><strong>Profile of <%= @profile.user.username %></strong></h1>
    <p><strong>Name: <%= @profile.firstname %> </strong></p>
    <p><strong>Bio:</strong></p>
    <p><%= @profile.bio %></p>
    <% if @profile.user == current_user %>
      <% link_to 'Edit', edit_profile_path(@profile) %>
    <% else %>
      <%= form_with(model: @profile.user, method: :patch) do |form| %>
        <%= form.hidden_field :toggle_follow, value: true %>
        <%= form.button 'Click Me', class:
        'btn btn-secondary' %>
    <% end %>
    
  </div>
<% end %>

app/views/static_pages/contact.html.erb
<h2>Contact Page</h2>

<%= form_for(:email) do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :email %>
  <%= form.text_field :email %>

  <%= form.label :message %>
  <%= form.text_area :message %>

  <%= form.submit "Send Message" %>
<% end %>